apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017 # Choose an available nodePort
  selector:
    app: mongo
  type: NodePort
