apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourlkafka
  namespace: kafka
spec:
  schedule: 0 * * * *
  template:
    includedNamespaces:
    - 'kafka'
    excludedNamespaces:
    includedResources:
    - '*'
    excludedResources:
    - storageclasses.storage.k8s.io
    includeClusterResources: null
    snapshotVolumes: true
    storageLocation: default
    volumeSnapshotLocations:
      - default
